<?php
/**
 * About With Feature Box 2
 *
 * @package Cardealer
 */

return array(
	'name'              => esc_html__( 'About With Feature Box 2', 'cardealer' ),
	'template_category' => esc_html__( 'About Us', 'cardealer' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
	<p>[vc_row full_width="stretch_row"][vc_column css=".vc_custom_1486033008921{background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][cd_space desktop="80" tablet="70" portrait="60" mobile="50" mobile_portrait="40"][vc_row_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-3" css=".vc_custom_1486530628902{margin-bottom: 30px !important;}"][cd_call_to_action icon_type="flaticon" icon_flaticon="glyph-icon flaticon-beetle" style="Default-Layout" title="New Vehicles" description="Get yourself nice and relaxed and settled. Concentrate on your breathing, engage in the" readmore="url:https%3A%2F%2Fcardealer.potenzaglobalsolutions.com%2Fcars%2F%3Fcar_condition%3Dnew%26cars_pp%3D12%26cars_order%3Dasc%26cars_grid%3Dyes%26lay_style%3Dview-grid-right" box_bg_image="1882"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-3" css=".vc_custom_1486530667077{margin-bottom: 30px !important;}"][cd_call_to_action icon_type="flaticon" icon_flaticon="glyph-icon flaticon-car-repair" style="Default-Layout" title="Vehicles Service" description="About something that you know you need to be doing, but are not. Then with that thing" readmore="url:https%3A%2F%2Fcardealer.potenzaglobalsolutions.com%2Fservice-01%2F|title:Service-1" box_bg_image="120"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-3" css=".vc_custom_1486530704809{margin-bottom: 30px !important;}"][cd_call_to_action icon_type="flaticon" icon_flaticon="glyph-icon flaticon-reparation" style="Default-Layout" title="Vehicles Parts" description="You will begin to realise why this exercise is called the Dickens Pattern reference" readmore="url:https%3A%2F%2Fcardealer.potenzaglobalsolutions.com%2Fservice-02%2F|title:service-2" box_bg_image="121"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-3" css=".vc_custom_1486530747953{margin-bottom: 30px !important;}"][cd_call_to_action icon_type="flaticon" icon_flaticon="glyph-icon flaticon-car" style="Default-Layout" title="Old Vehicles" description="Scrooge some different futures as you notice that the idea of this exercise is hypnotize" readmore="url:http%3A%2F%2Fcardealer.potenzaglobalsolutions.com%2Fcars%2F%3Fcar_condition%3Dused%26cars_pp%3D12%26cars_order%3Dasc%26cars_grid%3Dno%26lay_style%3Dview-list-right" box_bg_image="121"][/vc_column_inner][/vc_row_inner][cd_space desktop="20" tablet="20" portrait="15" mobile="10" mobile_portrait="10"][/vc_column][/vc_row][vc_section full_width="stretch_row" css=".vc_custom_1496473590275{background-image: url(https://sampledata.potenzaglobalsolutions.com/cardealer/wp-content/uploads/2017/01/04.jpg?id=6601) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="bg-cover-bottom sm-bg-hide"][vc_row full_width="stretch_row"][vc_column offset="vc_col-lg-6 vc_col-md-6"][vc_column_text]
<div class="custom-block-2">
<h4>Welcome to the Car dealer</h4>
Everything you need to build an amazing dealership website
Car Dealer is the best premium HTML5 Template. We provide everything you need to build an <strong>Amazing dealership website</strong> developed especially for car sellers, dealers or auto motor retailers.
<div class="ceo"><img class="alignnone size-full wp-image-7084" src="http://sample-data.potenzaglobal.com/cardealer/uploads/2017/03/signature.png" alt="" width="294" height="46" /></div>
<div class="ceo"><strong class="text-red">Car Dealer Founder</strong>
Kevin walsh</div>
</div>
[/vc_column_text][cd_space desktop="0" tablet="0" portrait="40" mobile="30" mobile_portrait="30"][/vc_column][vc_column el_class="box-border" offset="vc_col-lg-offset-1 vc_col-lg-5 vc_col-md-6" css=".vc_custom_1494505658624{background-color: #ffffff !important;}"][vc_row_inner][vc_column_inner el_class="col-xx-12" width="1/2" offset="vc_col-lg-6 vc_col-md-6 vc_col-xs-6"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-transport-3" element_id="44141a91-92ea-8" style="style-3" label="Vehicles Stock" counter="400" css=".vc_custom_1495536403668{padding-top: 15px !important;}"][/vc_column_inner][vc_column_inner el_class="col-xx-12" width="1/2" offset="vc_col-lg-6 vc_col-md-6 vc_col-xs-6" css=".vc_custom_1495173649316{padding-top: 20px !important;}"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-interface" element_id="44141a91-92ea-8" style="style-2" label="Dealer Reviews" counter="1000" css=".vc_custom_1493979082446{padding-top: 15px !important;}"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner el_class="col-xx-12" width="1/2" offset="vc_col-lg-6 vc_col-md-6 vc_col-xs-6"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-circle" element_id="44141a91-92ea-8" style="style-3" label="Happy Customer" counter="1500" css=".vc_custom_1495524651518{padding-bottom: 15px !important;}"][/vc_column_inner][vc_column_inner el_class="col-xx-12" width="1/2" offset="vc_col-lg-6 vc_col-md-6 vc_col-xs-6"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-cup" element_id="44141a91-92ea-8" style="style-2" label="Awards" counter="450" css=".vc_custom_1493979112655{padding-bottom: 15px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column][cd_space desktop="410" tablet="50" portrait="50" mobile="50" mobile_portrait="50"][/vc_column][/vc_row][/vc_section]</p>
<p>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>
CONTENT',
);
