<?php
/**
 * About Welcome Section
 *
 * @package Cardealer
 */

return array(
	'name'              => esc_html__( 'About Welcome Section', 'cardealer' ),
	'template_category' => esc_html__( 'About Us', 'cardealer' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_section full_width="stretch_row" css=".vc_custom_1497865934234{background-image: url(https://sampledata.potenzaglobalsolutions.com/cardealer/wp-content/uploads/2017/03/car-2-bg-1.png?id=6657) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="xs-bg-none"][vc_row][vc_column][cd_space tablet="70" portrait="60" mobile="50" mobile_portrait="40" desktop="80"][cd_section_title heading_tag="h1" section_number_tag="h1" title_align="text-center" section_title="Welcome to the Car dealer"][/cd_section_title][/vc_column][/vc_row][vc_row][vc_column width="1/2" offset="vc_col-xs-6"][/vc_column][vc_column width="1/2" offset="vc_col-lg-6 vc_col-md-6 vc_col-xs-12" css=".vc_custom_1497865587662{padding-left: 30px !important;}"][vc_raw_html css=".vc_custom_1496380215951{margin-bottom: 40px !important;}"]JTNDZGl2JTIwY2xhc3MlM0QlMjJjdXN0b20tYmxvY2stMiUyMiUzRSUzQ3NwYW4lM0VFdmVyeXRoaW5nJTIweW91JTIwbmVlZCUyMHRvJTIwYnVpbGQlMjBhbiUyMGFtYXppbmclMjBkZWFsZXJzaGlwJTIwd2Vic2l0ZSUyMCUzQyUyRnNwYW4lM0UlMEElMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NwJTNFQ2FyJTIwRGVhbGVyJTIwaXMlMjB0aGUlMjBiZXN0JTIwcHJlbWl1bSUyMFdvcmRwcmVzcyUyMFRoZW1lLiUyMFdlJTIwcHJvdmlkZSUyMGV2ZXJ5dGhpbmclMjB5b3UlMjBuZWVkJTIwdG8lMjBidWlsZCUyMGFuJTIwJTNDc3Ryb25nJTNFQW1hemluZyUyMGRlYWxlcnNoaXAlMjB3ZWJzaXRlJTNDJTJGc3Ryb25nJTNFJTIwJTIwZGV2ZWxvcGVkJTIwZXNwZWNpYWxseSUyMGZvciUyMGNhciUyMHNlbGxlcnMlMkMlMjBkZWFsZXJzJTIwb3IlMjBhdXRvJTIwbW90b3IlMjByZXRhaWxlcnMuJTNDJTJGcCUzRSUwQSUzQyUyRmRpdiUzRQ==[/vc_raw_html][vc_row_inner][vc_column_inner width="1/2" css=".vc_custom_1489154177465{margin-bottom: 30px !important;}"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-transport-3" element_id="7546369e-a550-2" style="style-2" label="Vehicles In Stock" counter="3968"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1489154190579{margin-bottom: 30px !important;}"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-interface" element_id="7546369e-a550-2" style="style-2" label="Dealer Reviews" counter="1500"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/2" css=".vc_custom_1489154199685{margin-bottom: 30px !important;}"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-circle" element_id="7546369e-a550-2" style="style-2" label="Happy Customers" counter="2000"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1489154209828{margin-bottom: 30px !important;}"][cd_counter counter_speed="10000" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-cup" element_id="7546369e-a550-2" style="style-2" label="Awards" counter="450"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column][cd_space tablet="40" portrait="30" mobile="20" desktop="50"][/vc_column][/vc_row][/vc_section]
CONTENT',
);
