<?php
/**
 * About Small Feature With Image
 *
 * @package Cardealer
 */

return array(
	'name'              => esc_html__( 'About Small Feature With Image', 'cardealer' ),
	'template_category' => esc_html__( 'About Us', 'cardealer' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
[vc_row 0=""][vc_column 0=""][cd_space tablet="70" portrait="60" mobile="50" mobile_portrait="40" desktop="80"][vc_row_inner 0=""][vc_column_inner el_class="custom-block-3" css=".vc_custom_1486718228833{margin-bottom: 30px !important;}" offset="vc_col-lg-6 vc_col-md-6"][vc_raw_html 0=""]JTNDZGl2JTIwY2xhc3MlM0QlMjJ0aXRsZSUyMiUzRSUzQ2gzJTNFQWJvdXQlMjBDYXJkZWFsZXIlM0MlMkZoMyUzRSUzQyUyRmRpdiUzRSUwQSUzQ2RpdiUyMGNsYXNzJTNEJTIyY29udGVudCUyMiUzRSUwQSUzQ2gyJTIwY2xhc3MlM0QlMjJ0ZXh0LXJlZCUyMiUzRTEwJTNDJTJGaDIlM0UlMEElM0NzdHJvbmclM0VFdmVyeXRoaW5nJTIweW91JTIwbmVlZCUyMHRvJTIwYnVpbGQlMjBhbiUyMGFtYXppbmclMjBkZWFsZXJzaGlwJTIwYXV0b21vdGl2ZSUyMHJlc3BvbnNpdmUlMjB3ZWJzaXRlLiUzQyUyRnN0cm9uZyUzRSUwQSUzQ3AlM0VDYXIlMjBEZWFsZXIlMjBpcyUyMHRoZSUyMGJlc3QlMjBwcmVtaXVtJTIwV29yZFByZXNzJTIwVGhlbWUuJTIwV2UlMjBwcm92aWRlJTIwZXZlcnl0aGluZyUyMHlvdSUyMG5lZWQlMjB0byUyMGJ1aWxkJTIwYW4lMjAlM0NiJTNFQW1hemluZyUyMGRlYWxlcnNoaXAlMjB3ZWJzaXRlJTNDJTJGYiUzRSUyMCUyMGRldmVsb3BlZCUyMGVzcGVjaWFsbHklMjBmb3IlMjBjYXIlMjBzZWxsZXJzJTJDJTIwZGVhbGVycyUyMG9yJTIwYXV0byUyMG1vdG9yJTIwcmV0YWlsZXJzLiUzQyUyRnAlM0UlMEElM0MlMkZkaXYlM0U=[/vc_raw_html][/vc_column_inner][vc_column_inner css=".vc_custom_1486718136547{margin-bottom: 30px !important;}" offset="vc_col-lg-6 vc_col-md-6"][vc_single_image source="external_link" alignment="center" custom_src="https://sampledata.potenzaglobalsolutions.com/cardealer/wp-content/uploads/2021/12/placeholder_562x224.png"][/vc_column_inner][/vc_row_inner][cd_space tablet="20" desktop="20"][vc_row_inner 0=""][vc_column_inner width="1/2" css=".vc_custom_1486718434321{margin-bottom: 30px !important;}" offset="vc_col-lg-3 vc_col-md-3"][cd_feature_box icon_type="flaticon" icon_flaticon="glyph-icon flaticon-beetle" hover_style="true" style="style-7" title="All brands" description="More than 100 brands"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1486718450228{margin-bottom: 30px !important;}" offset="vc_col-lg-3 vc_col-md-3"][cd_feature_box icon_type="flaticon" icon_flaticon="glyph-icon flaticon-interface-1" hover_style="true" style="style-7" title="Free Support" description="Premium and 24/7"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1486718465947{margin-bottom: 30px !important;}" offset="vc_col-lg-3 vc_col-md-3"][cd_feature_box icon_type="flaticon" icon_flaticon="glyph-icon flaticon-key" hover_style="true" style="style-7" title="Dealership" description="Single or multiple"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1486718482070{margin-bottom: 30px !important;}" offset="vc_col-lg-3 vc_col-md-3"][cd_feature_box icon_type="flaticon" icon_flaticon="glyph-icon flaticon-wallet" hover_style="true" style="style-7" title="Affordable" description="Best suitable price"][/vc_column_inner][/vc_row_inner][cd_space tablet="40" portrait="30" mobile="20" desktop="50"][/vc_column][/vc_row]
CONTENT',
);
