<?php // phpcs:ignore WordPress.Files.FileName.NotHyphenatedLowercase
/**
 * Color selectors
 *
 * @package cardealer
 */

global $cardealer_color_scheme_selectors, $cardealer_color_scheme_selectors_secondary, $cardealer_color_scheme_selectors_tertiary;

/**
 * Edit Below
 */

/**
 * Primary
 */

$cardealer_color_scheme_selectors['color'] = 'a, button, input, .text-red, .car-item .car-content a, .custom-block-1 a, .counter i, #header .topbar a:hover, #header.default-header .topbar li a:hover, .testimonial-1 .testimonial-block .testimonial-avtar h6, .testimonial-1 .testimonial-block:hover .testimonial-content i, .owl-carousel .owl-nav i, .call-to-action .border, .counter.icon b, .call-to-action i, .play-video .video-info a i, .feature-box i, .feature-box.left-align .icon i:before, .feature-box.left-align .icon i:before, .blog-2 .blog-content .blog-meta ul li a, .news-letter-main h4, .testimonial-4 .testimonial-block i, .feature-box.right-align .icon i:before, .isotope-filters  button.active, .isotope-filters  button:hover, .isotope .car-item-3 .car-popup a, .team .team-social a, .car-item .car-overlay-banner ul li a:hover, .tab-vertical.tabs-left .nav-tabs > li > a:hover, .tab-vertical.tabs-left .nav-tabs > li.active > a, ul.list li > i, .accordion .accordion-title a:hover, .accordion .accordion-title a:hover:after, .widget.widget_archive ul li:hover > a, .widget.widget_categories ul li:hover > a, .widget.widget_recent_comments ul li a:hover, .widget_archive ul li:hover i, .widget.widget_pages ul li:hover > a, .car-details .car-price .new-price, ul.list-col-2 li i, ul.list-col-3 li i, .tab-isotope-2 .list-style-1 li i, .tab-isotope-2 div i, ul.list-col-4 li i, .entry-meta ul li i, .entry-meta i, .entry-title a:hover, .entry-meta ul li a:hover, .entry-meta a:hover, .comments-1 .comments-info a, .woocommerce .star-rating span:before, .widget.woocommerce ul.product_list_widget  li a:hover, .widget.woocommerce ul.product_list_widget li ins .amount, .woocommerce .comment-form-rating p.stars a, .single-product .shipping-taxable .entry-summary .price ins .amount, .single-product .shipping-taxable .entry-summary .price ins .amount span, .woocommerce .cart-collaterals .cart_totals .order-total .amount, .woocommerce .woocommerce-checkout-review-order table tfoot .order-total .amount, .woocommerce .woocommerce-info:before, .woocommerce-MyAccount-navigation ul li.is-active a, .blog-2 .blog-description a:hover, .blog-1 .blog-content a.link:hover, .content-box-5 a:hover, .tab-vertical.tabs-left .nav-tabs > li.active > a:before, #tabs ul.tabs li.active, #tabs ul.tabs li.active:focus, #tabs ul.tabs li:hover, .widget_breadcrumb_navxt a, .product-listing .car-grid .car-title a:hover, .product-listing .car-grid .price span, .button.white, .mega-menu .menu-links > li.current-menu-item > a, #mega-menu-wrap-primary-menu #mega-menu-primary-menu > li.mega-menu-item.mega-current-menu-item > a, #header #mega-menu-wrap-primary-menu #mega-menu-primary-menu > li.mega-menu-item.mega-current-menu-ancestor > ul.mega-sub-menu > li.mega-current-menu-item > a, .countdown li span, .topbar_item_type-woo_cart .drop-content .price, .feature-box.left-icon.box-hover:hover .content h6, .feature-box.right-icon.box-hover:hover .content h6, .social.style-1 a:hover i, .bbp-forums a, #buddypress a.activity-time-since, #header.transparent-fullwidth .mega-menu .menu-links > li.current-menu-ancestor > a, .sort-filters-box .stripe, .sidebar .cars_filters .cars-total-vehicles .stripe, .cars-top-filters-box-left #slider-amount, .widget.widget_rss ul li a, .widget.widget_recent_comments ul li a, .modal .close, .woocommerce table.order_details tfoot tr .amount, .woocommerce .product_cat-clothing p.price span, .error-page .error-content p a, .widget_breadcrumb_navxt a:hover, .woocommerce-MyAccount-navigation ul li a:hover, .woocommerce-MyAccount-navigation ul li.is-active a, .table-scroll .compare-list .price .new-price, .blog .blog-2 .blog-description .read-more, cite, blockquote cite, #cancel-comment-reply-link, .comments-1 .comments-info .comment-date a:hover, .entry-title i, .widget ul li > a:hover, .widget_recent_entries .recent-post-info a:hover, .cd_maintenance .footer-widget a, ul.page-breadcrumb li:hover:before, ul.page-breadcrumb li:hover span, .item-listing > .item > .portfolio-item .portfolio-caption a:hover, .related-work .blog-related-posts-carousel .item > .portfolio-item .portfolio-caption a:hover, .promocode-box h4, .feature-box.default-feature.box-hover:hover .content h6, #header.default-header #primary-menu > li.menu-item.current-menu-item > a, #header.default-header #primary-menu > li.menu-item > a:hover, #header.default-header #primary-menu > li > .menu-item-woocommerce-cart-wrapper > a:hover, #header.default-header #primary-menu > li > .searchform .search > a:hover, #header.default-header #primary-menu > li.current-menu-ancestor > a, .footer .layout_2 .social ul li a:hover i, .wpb-js-composer .vc_tta.vc_tta-style-modern .vc_tta-panel .vc_tta-panel-title:hover>a, .potenza-custom-menu.horizontal ul.menu li:hover, .potenza-custom-menu.horizontal ul.menu li.glyph-icon:hover, .potenza-custom-menu.horizontal ul.menu li.active, .potenza-custom-menu.horizontal ul.menu li:hover a, .potenza-custom-menu.horizontal ul.menu li.glyph-icon:hover:before, .potenza-custom-menu.horizontal ul.menu li.active a, .potenza-custom-menu.horizontal ul.menu li.glyph-icon.active:before, .potenza-custom-menu.vertical ul.menu li:hover a, .potenza-custom-menu.vertical ul.menu li.glyph-icon:hover:before, .modal .modal-body a.cd-policy-terms, .modal .modal-body a.cd-policy-terms:hover, .footer .widget .widget-menu li a:hover, .footer .widget_categories .widget-menu li a:hover span, .product-listing.lazyload .sidebar .cars_filters .widgettitle a, .pricing-title .pricing-prize h2, .blog-2 .blog-content .blog-admin span a:hover, #header .topbar .language a.cardealer-current-lang:hover, #header .topbar .language a.cardealer-current-lang:hover, .language .drop-content a:hover, #header.defualt-header.boxed .topbar .language a:hover, #header .topbar .language .drop-content a:hover, #header.light .topbar .language .drop-content a:hover, #header.light-fullwidth .topbar .language .drop-content a:hover, #header.logo-center .topbar .language .drop-content a:hover, #header.logo-right .topbar .language .drop-content a:hover, #header.boxed .topbar .language .drop-content a:hover, #header .topbar .language a.cardealer-current-lang:hover, #header .topbar .language a.cardealer-current-lang:hover, .language .drop-content a:hover, #header .topbar .language .drop-content a:hover, #header .topbar .language ul li a:hover .lang-label, #header .topbar .language.style-horizontal ul li a:hover .lang-label, #header.defualt .topbar .language ul li a:hover .lang-label, #header.transparent-fullwidth .topbar .language ul li a:hover .lang-label, #header.defualt .topbar .language.style-horizontal ul li a:hover .lang-label, #header.transparent-fullwidth .topbar .language.style-horizontal ul li a:hover .lang-label, .style-classic.car-grid .car-bottom .car-bottom-actions li a i, .style-classic.car-grid .car-bottom .car-bottom-actions li a:hover,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item.mega-current_page_ancestor > .mega-menu-link,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item.mega-current-menu-parent > .mega-menu-link,
	#header.header-color-default .mega-menu.desktopTopFixed #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item.mega-current_page_ancestor > .mega-menu-link,
	#header.header-color-default .mega-menu.desktopTopFixed #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item.mega-current-menu-parent > .mega-menu-link,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item.mega-current-menu-item > .mega-menu-link,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item:hover > .mega-menu-link,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item > .mega-menu-link:hover,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item:hover > .mega-menu-link:hover,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .menu-item .menu-item-woocommerce-cart-wrapper > a:hover,
	#header.header-color-default .mega-menu #mega-menu-wrap-primary-menu #mega-menu-primary-menu .menu-item .search > .search-open-btn:hover,
	#header.header-color-default .mega-menu.desktopTopFixed #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item.mega-current-menu-item > .mega-menu-link,
	#header.header-color-default .mega-menu.desktopTopFixed #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item:hover > .mega-menu-link,
	#header.header-color-default .mega-menu.desktopTopFixed #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item > .mega-menu-link:hover,
	#header.header-color-default .mega-menu.desktopTopFixed #mega-menu-wrap-primary-menu #mega-menu-primary-menu .mega-menu-item:hover > .mega-menu-link:hover,
	.mega-menu .drop-down-multilevel li:hover > a,
	.mega-menu .drop-down-multilevel li:hover > a i.fa,
	#header.default-header.defualt #primary-menu > li.menu-item.current-menu-item > a,
	#header.default-header.defualt #primary-menu > li.menu-item.current-menu-ancestor > a,
	#header.default-header.defualt #primary-menu > li.menu-item > a:hover,
	#header.default-header.defualt #primary-menu > li > .menu-item-woocommerce-cart-wrapper > a:hover,
	#header.default-header.defualt #primary-menu > li > .searchform .search > a:hover,
	#header.default-header.transparent-fullwidth #primary-menu > li.menu-item.current-menu-item > a,
	#header.default-header.transparent-fullwidth #primary-menu > li.menu-item.current-menu-ancestor > a,
	#header.default-header.transparent-fullwidth #primary-menu > li.menu-item > a:hover,
	#header.default-header.transparent-fullwidth #primary-menu > li > .menu-item-woocommerce-cart-wrapper > a:hover,
	#header.default-header.transparent-fullwidth #primary-menu > li > .searchform .search > a:hover,
	.mega-menu .menu-links .current-menu-item > a,
	.car-details.car-detail-layout-modern-1 .car-detail-post-option > ul li a i,
	.car-details.car-detail-layout-modern-1 .car-detail-post-option .single-share-box li a,
	.car-details.car-detail-layout-modern-1 .car-detail-post-option .single-share-box li a:hover,
	.car-details .col-sm-12 .car-detail-post-option > ul li a i,
	.car-details .col-sm-12 .car-detail-post-option .single-share-box li a,
	.car-details .col-sm-12 .car-detail-post-option .single-share-box li a:hover,
	body .car-details #tab-accordion .panel-heading.active .panel-title,
	#comparelist .modal-content .ui-sortable-handle .cardealer-vehicle-compare-list-row .compare-remove-column,
	#tabs ul.tabs li.active,
	#tabs ul.tabs li.active:focus,
	#tabs ul.tabs li:hover,
	.cardealer-tabs ul.tabs li.active,
	.cardealer-tabs ul.tabs li.active:focus,
	.cardealer-tabs ul.tabs li:hover,
	.cardealer-faq-tabs ul.tabs li.active,
	.cardealer-faq-tabs ul.tabs li.active:focus,
	.cardealer-faq-tabs ul.tabs li:hover,
	.cd-share-button.default .share .single-share-box li a,
	.cd-video-button .popup-youtube i,
	.cd-compare-button .pgs_compare_popup i,
	.cd-wishlist-button .pgs_wishlist i,
	.cd-vehicle-buttons.cd-vehicle-buttons-style-2 .details-nav .vehicle-buttons li a i,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-tabs .tabcordion-tab.active,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-tabs .tabcordion-tab:hover,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-contents .panel-heading .panel-title .tabcordion-collapse:not(.collapsed),
	.cardealer-dashboard-navigation li.is-active a,
	.cardealer-dashboard-user-info .cardealer-dashboard-user-info--profile-type,
	.cardealer-dashboard-user-info .cardealer-dashboard-user-info--profile-title:hover,
	.cardealer-dashboard-content .dashboard-content-inner .dashboard-content-item .dashboard-item-icon,
	.cardealer-dashboard-content-header .cardealer-dashboard-content-header-logout:hover i,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .car-price .new-price,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-items-bottom-actions i,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-item-title a:hover,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-items-bottom-actions li a:hover,
	.cardealer-dashboard-content .cardealer-dashboard-subs-table td.woocommerce-orders-table__cell-subscription-id a:hover,
	.cardealer-userdash-content .cardealer-userdash-tabs .nav-tabs li.active a,
	.cardealer-userdash-content .cardealer-userdash-tabs .all-cars-list-arch .car-grid .car-title a:hover,
	.all-cars-list-arch .car-grid .car-details .car-list-seller-info .seller-info-details .seller-info-title a:hover,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-row-right .cdfs-review-data-inner span,
	.cd-vehicle-seller-info .vehicle-seller-info-details .vehicle-seller-info-author a:hover,
	.cd-vehicle-seller-info .vehicle-seller-info-details .vehicle-seller-info-phone i,
	.cdfs-dealers-wrapper .cdfs-dealers-list-wrapper .cdfs-dealers-list td a:hover,
	.mega-menu .widget_shopping_cart_content ul.cart_list li .variation .variation-OrderType p,
	.cdfs-av-sections .cdfs-av-section-cars-location .cdfs-av-section-content p a:hover,
	.cdfs-av-section-cars-image-gallery .cdfs-image-upload .select-file-note span,
	.cardealer-share .cardealer-share-modal .cardealer-share-links .cardealer-share-items li a,
	.cars_search .cd-search-wrap .cd-search-submit,
	.menu-search-wrap.cd-search-wrap .cd-search-submit,
	.cd-search-wrap .cd-search-autocomplete-list li:hover .search-result-name,
	.overview-share .info a:hover,
	.cars-top-filters-box.cars-filters-mobile .cars-total-vehicles .stripe,
	.vehicle-compare-main-content-remove-link .compare-remove-column:hover

	.cars_filters .stripe-item li span,
	.cdhl-vehicle-filters .stripe-item li span,
	.elementor-widget-cdhl_vehicles-listing-search .cd-search-wrap .cd-search-submit,
	.cdhl-vehicles-listing-search-filter .cd-search-wrap .cd-search-submit,
	.elementor-widget-cdhl_vehicles-listing-filters .cars-total-vehicles .stripe,
	.cdhl_vehicles-listing-filters_wrapper .cars-total-vehicles .stripe,
	.elementor-widget-cdhl_vehicles-listing .vehicle-listing-view-list .car-grid .car-title a:hover,
	.cdhl_vehicles-listing_wrapper .vehicle-listing-view-list .car-grid .car-title a:hover,
	.sort-filters-box .stripe-item li a span,
	.cars_filters .cars-total-vehicles .stripe-item li:hover a span,
	.cdhl-vehicle-filters .cars-total-vehicles .stripe-item li:hover a span';

// Color with Important.
$cardealer_color_scheme_selectors['color-imp'] = '
	.feature-box.style-5.box-hover:hover .content h6,
	.feature-box.style-6.box-hover:hover .content h6,
	.cdfs-av-section-cars-image-gallery .cdfs-image-upload .select-file-note span';

$cardealer_color_scheme_selectors['background-color'] = '.button, .button.black:before, .topbar_item_type-woo_cart .shop .badge, .section-title .separator:before, .section-title .separator:after, .feature-box.round-icon h6:before, .skills-2 .bar, .maintenance-progress-bar .progress-bar .rotate, .maintenance-progress-bar .progress-bar .right, .counter h6:before, .owl-carousel .owl-dots .owl-dot.active span, .widget .widgettitle:before, .widget .wp-block-group__inner-container > h2:before, .button.border:before, .blog-1 .blog-content a.link:before, .owl-carousel .owl-nav i:hover, .owl-carousel .owl-dots .owl-dot:hover span, .feature-box.round-border.box-hover:hover .icon i, .timeline > li:hover > .timeline-panel, .timeline > li:hover > .timeline-badge, .timeline .timeline-heading h5:before, .car-item:hover .separator:before, .car-item:hover .separator:after, .testimonial-2 .testimonial-content, .call-to-action .border, .ui-slider .ui-widget-header, .woocommerce .widget_price_filter .ui-slider .ui-slider-range, .feature-box.left-align.box-hover:hover, .feature-box.right-align.box-hover:hover, .car-item-2 .price, .blog-2 .blog-image .date-box span, .blog-2 .blog-description .separator:before, .blog-2 .blog-description .separator:after, .testimonial-3 .testimonial-content, .q-link.box-hover:hover, .share .blog-social li a, .isotope .car-item-3 .car-overlay, .team:hover, .isotope .car-item-3 .car-popup a:hover, .team .team-social li a:hover, .search-block.red-bg, .feature-box.round-icon.box-hover:hover i, .opening-hours h6:before, .team-2 .team-social ul li a, .accordion .accordion-title a.active, .widget_calendar #wp-calendar td#today, .widget_tag_cloud ul li a:hover, .pagination li a:focus, .pagination li a:hover, .pagination li span:focus, .pagination li span:hover, .pagination li span.current, .details-nav ul li a:hover, .car-details-sidebar h5:before, .car-details-sidebar h6:before, .share .single-share-box li a, .fuel-efficiency-detail, .share .share-button, .pagination > .active > a, .pagination > .active > a:focus, .pagination > .active > a:hover, .pagination > .active > span, .pagination > .active > span:focus, .pagination > .active > span:hover, .woocommerce ul.products li.product .add_to_cart_button, .woocommerce div.product form.cart .single_add_to_cart_button, .woocommerce .woocommerce-message .button, .woocommerce-cart .cart_totals .checkout-button.alt, .related.products .owl-carousel .owl-item .item .button, .woocommerce nav.woocommerce-pagination ul li a:focus, .woocommerce nav.woocommerce-pagination ul li a:hover, .woocommerce nav.woocommerce-pagination ul li span.current, .pagination ul li a:focus, .pagination ul li a:hover, .pagination ul li span.current, .woocommerce footer .button, .woocommerce .widget_shopping_cart_content .button, .woocommerce .sidebar .button, .woocommerce footer .button:hover, .woocommerce .widget_shopping_cart_content .button:hover, .woocommerce .sidebar .button:hover, .tagcloud a:hover, .widget.woocommerce input[type=submit], .woocommerce div.product .woocommerce-tabs ul.tabs li.active a, .woocommerce div.product .woocommerce-tabs .wc-tab h2:before, .woocommerce #review_form .comment-reply-title:before, .woocommerce div.product .woocommerce-tabs ul.tabs li, .woocommerce #respond input#submit, .woocommerce div.product .woocommerce-tabs ul.tabs li.active:hover a, .woocommerce .woocommerce-message .button:hover, .woocommerce-cart table.shop_table.cart .button, .woocommerce-cart table.shop_table.cart .coupon + .button:hover, .woocommerce-cart .cart_totals .checkout-button.alt:hover, .woocommerce .woocommerce-checkout h3:before, #add_payment_method #payment div.form-row #place_order, .woocommerce-cart #payment div.form-row #place_order, .woocommerce-checkout #payment div.form-row #place_order, .woocommerce-account form .button, .woocommerce .woocommerce-info .button, .woocommerce .woocommerce-info .button:hover, .woocommerce-MyAccount-content table.my_account_orders td .button, .woocommerce-checkout .woocommerce form.login .button, .woocommerce-checkout .woocommerce form.checkout_coupon .button, .product-listing .car-grid .car-title a:before, .car-details .slider-for .slick-prev:hover, .car-details .slider-for .slick-prev:focus, .car-details .slider-for .slick-next:hover, .slider-for .slick-next:focus, .tags-2 ul li a:hover, .theme-bg, .custom-block-3 .title h3:before, .menu-item-woocommerce-cart-wrapper .woo-cart-details.count, .woocommerce-MyAccount-content table.my_account_orders td .button, .woocommerce-order-details table.my_account_orders td .button, .widget .widgettitle::before, .woocommerce .return-to-shop a.button, .woocommerce .return-to-shop a.button:hover, .mega-menu a.button.wc-forward, .mega-menu a.button.wc-forward:hover, .topbar_item_type-woo_cart .drop-content .checkout a, .button.gray:before, .social.style-2 a:hover i, .social.style-3 a i, #buddypress #item-nav .item-list-tabs#object-nav ul li.selected a, #buddypress #item-body .item-list-tabs#subnav ul li.selected a, .car-detail-post-option > ul li a i, .woocommerce-order-received .woocommerce h2:before, .woocommerce-MyAccount-content .woocommerce-order-details__title:before, .woocommerce-MyAccount-content .woocommerce-column__title:before, .title-underline:before, .widget .widgettitle::before, .woocommerce .woocommerce-info .button, .comments-info .reply .comment-reply-link, .footer h6:before, .ui-state-default.ui-state-active, .ui-widget-content .ui-state-default.ui-state-active, .cd_maintenance .footer-widget .footer-widget-social li a:hover, .sidebar-widget #searchsubmit, body.single-cars  .car-details-sidebar .woocommerce.add_to_cart_inline .button, .topbar .top-promocode-box .button::before, .slider-content.vehicle-search-section .search-tab ul.tabs li.active, .slider-content.vehicle-search-section .search-tab ul.tabs li.active:focus, .slider-content.vehicle-search-section .search-tab ul.tabs li:hover, .search-logo ul.tabs li.active, .search-logo ul.tabs li.active:focus, .search-logo ul.tabs li:hover, .cars_condition_carousel-wrapper .cardealer-tabs .tabs li.active, .cars_condition_carousel-wrapper .cardealer-tabs .tabs li.active:focus, .cars_condition_carousel-wrapper .cardealer-tabs .tabs li:hover, .overview-share .share .cardealer-share a:hover, .wpb-js-composer .vc_tta.vc_general.vc_tta-tabs.vc_tta-style-flat li.vc_tta-tab.vc_active a, .wpb-js-composer .vc_tta.vc_general.vc_tta-tabs.vc_tta-style-flat li.vc_tta-tab:hover a, .wpb-js-composer .entry-content .vc_tta.vc_tta-style-flat .vc_tta-panel.vc_active .vc_tta-panel-title > a, .wpb-js-composer .vc_tta.vc_general.vc_tta-accordion.vc_tta-style-flat .vc_tta-panel-heading:hover, .wpb-js-composer .vc_tta.vc_general.vc_tta-accordion.vc_tta-style-outline .vc_tta-panel.vc_active .vc_tta-panel-heading, .wpb-js-composer .vc_tta.vc_general.vc_tta-accordion.vc_tta-style-outline .vc_tta-panel-heading:hover, #header .menu .menu-inner div > .row #primary-menu > li.menu-item.cdfs-add-vehicle > a, #header .menu .menu-inner div > .row #mega-menu-primary-menu > li.menu-item.cdfs-add-vehicle > a, .slick_sider.video-slider .slick-prev, .slick_sider.video-slider .slick-next, .potenza-custom-menu.horizontal ul.menu li, .feature-box.feature-border.round-icon h6:before, .feature-box.feature-border.style-4 h6:before, .feature-box.feature-border.style-5 h6:before, .feature-box.feature-border.style-6 h6:before, .feature-box.feature-border.style-7 h6:before, .feature-box.feature-border.style-8 h6:before, .feature-box.feature-border.style-9 h6:before, .woocommerce-checkout .select2-dropdown .select2-results__option.select2-results__option--highlighted, .product-listing.lazyload .widget.widget_search #searchsubmit, .widget_search .wp-block-search__inside-wrapper .wp-block-search__button, .product-listing.default .widget.widget_search #searchsubmit, .pricing-table.active .pricing-title h2.text-bg, .pricing-table.active .pricing-order, .search-logo-box:hover span, .style-classic.car-item .car-content ul.car-bottom-actions.classic-grid li a:hover, .style-classic.car-item .car-content ul.car-bottom-actions.classic-grid li a.popup-youtube:hover, .mega-menu .menu-item-compare .compare-details.count, .widget_tag_cloud .tagcloud a:hover, .potenza-custom-menu.horizontal.sticky, .widget.widget-vehicle-categories .cat-item a:hover > .count,
	#header .mega-menu a.button.wc-forward,
	#header .mega-menu a.button.checkout.wc-forward:before,
	#header.header-color-default .mega-menu .cart-contents .woo-cart-details.count, .wpcf7-form input[type="submit"],
	.car-buy-online-btn:hover,
	.car-details-sidebar .vehicle-detail-trade-in-appraisal-wrap .dealer-form-btn:before,
	.car-details.car-detail-layout-modern-1 .aside-lead-form-btn li a:hover,
	.car-details .col-lg-12 .aside-lead-form-btn li a:hover,
	.slider-slick .my-gallery .watch-video-btn .play-video .popup-youtube,
	.car-details .vehicle-subtitle-attributes li:after,
	.car-details .slick-slider .slick-prev:hover,
	.car-details .slick-slider .slick-prev:focus,
	.car-details .slick-slider .slick-next:hover,
	.year-range-slide .slider-year-range .ui-slider-handle,
	.price-slide .slider-range .ui-slider-handle,
	.cdfs-my-user-account-navigation li.is-active a,
	.cdfs-my-user-account-navigation li.cars-available,
	.vehicle-element-title:before,
	.cd-video-button.rounded .popup-youtube i,
	.cd-compare-button.rounded .pgs_compare_popup i,
	.cd-wishlist-button.rounded .pgs_wishlist i,
	.cd-vehicle-buttons.cd-vehicle-buttons-color-theme .details-nav .vehicle-buttons li a,
	.cd-vehicle-buttons.cd-vehicle-buttons-color-dark .details-nav .vehicle-buttons li a:before,
	.cd-vehicle-buttons.cd-vehicle-buttons-style-2.cd-vehicle-buttons-type-rounded .details-nav .vehicle-buttons li a i,
	.cd-vehicle-seller-email-btn a:hover,
	.cardealer-dashboard-content-header .cardealer-dashboard-content-header-add-car,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-item .cardealer-list-item-overlay a,
	.cardealer-dashboard-content .cdfs-edit-account-form .setting-checkbox input:checked + span,
	.cardealer-userdash-header .cardealer-userdash-userinfo .cardealer-userdash-buttons .cardealer-userdash-btn-white:hover,
	.cardealer-userdash-header .cardealer-userdash-userinfo .cardealer-userdash-buttons .cardealer-userdash-btn-red,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-item .cdfs-remove-wishlist,
	.cardealer-userdash-content .cardealer-userdash-tabs .all-cars-list-arch .car-grid .car-title a:before,
	.cd-vehicle-seller-contact-form .vehicle-seller-contact-title:before,
	.widget.widget-cdfs-vehicle-seller-contact .vehicle-seller-contact-title:before,
	.order-info,
	.woocommerce .woocommerce-form-track-order .button,
	.woocommerce .woocommerce-form-track-order .button:hover,
	.woocommerce-order-details .order-again .button,
	.woocommerce-order-details .order-again .button:hover,
	.woocommerce-Reviews .comment-form .form-submit .submit,
	.cdfs-dealers-wrapper .cdfs-dealers-search-form .cdfs-dealers-search-tools .cdfs-dealers-search-search button,
	.cdfs-dealers-wrapper .cdfs-dealers-search-form .cdfs-dealers-search-tools .cdfs-dealers-search-reset button:hover,
	.featured-vehicles-listing-wrapper .featured-vehicles-listing-section-title,
	.product-listing .featured-vehicles-listing-wrapper:before,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-item-view-statistics .item-view-statistics,
	.woocommerce-MyAccount-content .woocommerce-pagination .woocommerce-button,
	.woocommerce-MyAccount-content .woocommerce-pagination .woocommerce-button:hover,
	.woocommerce-MyAccount-content a.button,
	.woocommerce-MyAccount-content a.button:hover,
	.subscriptio-account-subscription-orders h2:before,
	.cardealer-share .cardealer-share-modal .cardealer-share-links .cardealer-share-items li a:hover,
	.car-details .cardealer-share-has-inline-links .cardealer-share-action-item .cardealer-share-action-link,
	.entry-share .entry-footer-share .cardealer-share .cardealer-share-action-link,
	.cdhl-mailchimp .mc4wp-form > .mc4wp-form-fields input[type="submit"],
	.car-item .car-content .cardealer-lead-form-req-price-btn:hover,
	.car-details .cardealer-lead-form-req-price-btn:hover,
	.cardealer-dashboard-content .cardealer-lead-form-req-price-btn:hover,
	.cd-vehicle-compare-wrapper .cd-vehicle-compare td .cardealer-lead-form-req-price-btn:hover,
	.compare-list .cardealer-vehicle-compare-list-row .cardealer-lead-form-req-price-btn:hover,
	.select2-container.select2-container--default .select2-results__option[aria-selected=true]:hover,
	.select2-container.select2-container--default .select2-results__option--highlighted[aria-selected],

	.elementor-widget-cdhl_vehicles-listing-search .title:before,
	.elementor-widget-cdhl_vehicles-listing-price-filter .title:before,
	.elementor-widget-cdhl_vehicles-listing-filters .title:before,
	.cdhl-vehicles-listing-search-filter .title:before,
	.cdhl_vehicles-listing-price-filter_wrapper .title:before,
	.cdhl_vehicles-listing-filters_wrapper .title:before,
	.elementor-widget-cdhl_vehicles-listing .vehicle-listing-view-list .car-grid .car-title a:before,
	.cdhl_vehicles-listing_wrapper .vehicle-listing-view-list .car-grid .car-title a:before';

// Background color with Opacity.
$cardealer_color_scheme_selectors['background'] = '.play-video .video-info:before, .car-item .car-overlay-banner';

// Background color with Important.
$cardealer_color_scheme_selectors['background-imp'] = '
	#page .theme-bg,
	.theme-bg .vc_row-background-overlay,
	#header.default-header.boxed .topbar,
	.skills-2 .bar,
	.cdfs-av-sections .cdfs-av-section .cdfs-av-title:before';

$cardealer_color_scheme_selectors['border-color'] = '#header .mega-menu .widget_shopping_cart_content, .button.border:hover, .button.border:focus, .button.border:active, .search-box, .owl-carousel .owl-nav i:hover, .menu-item-search .search .search-box input:focus, .feature-box.round-border.box-hover:hover .icon, .feature-box-3.box-hover:hover .icon i, .testimonial-2 .testimonial-info .testimonial-avatar img, .ui-state-default, .ui-widget-content .ui-state-default, .ui-widget-header .ui-state-default, .woocommerce .widget_price_filter .ui-slider .ui-slider-handle, .form-group input:focus, .news-letter input:focus, .form-group textarea:focus, .wpcf7-form input[type="text"]:focus, .wpcf7-form input[type="email"]:focus, .wpcf7-form input[type="url"]:focus, .wpcf7-form input[type="tel"]:focus, .wpcf7-form input[type="number"]:focus, .wpcf7-form input[type="date"]:focus, .wpcf7-form select:focus, .wpcf7-form textarea:focus, .accordion .accordion-title a.active, .widget_search input:focus, .widget_search .wp-block-search__inside-wrapper .wp-block-search__input:focus, .widget_tag_cloud ul li a:hover, .form-control:focus, .pagination li a:focus, .pagination li a:hover, .pagination li span:focus, .pagination li span:hover, .pagination li span.current, .details-nav ul li a:hover, .pagination > .active > a, .pagination > .active > a:focus, .pagination > .active > a:hover, .pagination > .active > span, .pagination > .active > span:focus, .pagination > .active > span:hover, .section-field input:focus, .section-field textarea:focus, .post-password-form input[type="password"]:focus, .woocommerce nav.woocommerce-pagination ul li a:focus, .woocommerce nav.woocommerce-pagination ul li a:hover, .woocommerce nav.woocommerce-pagination ul li span.current, .pagination ul li a:focus, .pagination ul li a:hover, .pagination ul li span.current, .tagcloud a:hover, .widget.woocommerce input.search-field:focus, .woocommerce .comment-form input[type="text"]:focus,
.woocommerce .comment-form input[type="email"]:focus, .woocommerce .comment-form textarea:focus, .woocommerce-account .woocommerce form .input-text:focus, .car-details .slider-for .slick-prev:hover, .car-details .slider-for .slick-prev:focus, .car-details .slider-for .slick-next:hover, .slider-for .slick-next:focus, .tags-2 ul li a:hover, .woocommerce-MyAccount-navigation ul li a:hover, .woocommerce-MyAccount-navigation ul li.is-active a, .table-scroll .compare-list td .remove, .news-letter-main .news-letter-form input:focus, #inquiry-form .form-control:focus, #inquiry-form .form-controltextarea:focus, .footer .news-letter .form-control:focus, .wpcf7-form .contact-form.appointment-form.appointment-form-light input[type="text"]:focus, .wpcf7-form .contact-form.appointment-form.appointment-form-light input[type="email"]:focus, .wpcf7-form .contact-form.appointment-form.appointment-form-light textarea:focus, .product-listing.lazyload .widget.widget_search input:focus, .product-listing.default .widget.widget_search input:focus, .widget.widget-vehicle-categories .cat-item a:hover > .count,
	.car-details.car-detail-layout-modern-1 .aside-lead-form-btn li a:hover,
	.car-details .col-lg-12 .aside-lead-form-btn li a:hover,
	.car-details .slick-slider .slick-prev:hover,
	.car-details .slick-slider .slick-prev:focus,
	.car-details .slick-slider .slick-next:hover,
	.cd-vehicle-seller-email-btn a:hover,
	.cardealer-dashboard-user-info .cardealer-dashboard-user-info--profile-img img,
	.cardealer-dashboard-content .dashboard-content-inner .dashboard-content-item a:hover,
	.cardealer-dashboard-content-header .cardealer-dashboard-content-header-logout:hover i,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid:hover,
	.cardealer-dashboard-content .cdfs-edit-account-form .cdfs-form-row .cdfs-input:focus,
	.cardealer-dashboard-content .cdfs-edit-account-form .cdfs-form-row .cdfs-input:focus-visible,
	.cardealer-dashboard-content .cdfs-edit-account-form .setting-checkbox input:checked + span,
	.cardealer-userdash-header .cardealer-userdash-userinfo .cardealer-userdash-buttons .cardealer-userdash-btn,
	.cardealer-userdash-content .cardealer-userdash-tabs .cardealer-userdash-tab-content .wpcf7-form .wpcf7-form-control-wrap > .wpcf7-form-control:focus,
	.cdfs-user-form .cdfs-input-wrap input:focus,
	.cdfs_lost_user_password .cdfs-input-wrap input:focus,
	.cardealer-userdash-content .cardealer-userdash-tabs .cdfs-form-row .cdfs-input:focus,
	.cardealer-userdash-content .cardealer-userdash-tabs .cdfs-form-row .cdfs-input:focus-visible,
	.cd-vehicle-seller-info .vehicle-seller-info-thumb img,
	.cd-vehicle-seller-contact-form .wpcf7 .wpcf7-form .wpcf7-form-control-wrap > .wpcf7-form-control:focus,
	.widget.widget-cdfs-vehicle-seller-contact .wpcf7 .wpcf7-form .wpcf7-form-control-wrap > .wpcf7-form-control:focus,
	.woocommerce-Reviews .comment-form input[type="text"]:focus,
	.woocommerce-Reviews .comment-form input[type="email"]:focus,
	.woocommerce-Reviews .comment-form textarea:focus,
	.cdfs-dealers-wrapper .cdfs-dealers-search-form .cdfs-dealers-search-tools .cdfs-dealers-search-reset button,
	.cardealer-share .cardealer-share-modal .cardealer-share-links .cardealer-share-items li a:hover,
	.cdhl-mailchimp .mc4wp-form > .mc4wp-form-fields input:focus,
	.cdhl-mailchimp.mailchimp-color-light .mc4wp-form > .mc4wp-form-fields input:focus';

$cardealer_color_scheme_selectors['border-color-imp'] = '.form-group input:focus';

$cardealer_color_scheme_selectors['border-top-color'] = '.testimonial-2 .testimonial-content:before,
	.testimonial-3 .testimonial-content:before,
	.woocommerce .woocommerce-info,
	.mega-menu .drop-down-multilevel,
	#header #mega-menu-wrap-primary-menu #mega-menu-primary-menu li.mega-menu-item > ul.mega-sub-menu,
	.cardealer-userdash-content .cardealer-userdash-tabs .nav-tabs li.active a,
	.cd-vehicle-seller-info';

$cardealer_color_scheme_selectors['border-bottom-color'] = '.isotope-filters  button.active, .isotope-filters  button:hover, #tabs ul.tabs li.active, #tabs ul.tabs li.active:focus, #tabs ul.tabs li:hover, body .car-details #tab-accordion .panel-heading.active .panel-title,
	#tabs ul.tabs li.active,
	#tabs ul.tabs li.active:focus,
	#tabs ul.tabs li:hover,
	.cardealer-tabs ul.tabs li.active,
	.cardealer-tabs ul.tabs li.active:focus,
	.cardealer-tabs ul.tabs li:hover,
	.cardealer-faq-tabs ul.tabs li.active,
	.cardealer-faq-tabs ul.tabs li.active:focus,
	.cardealer-faq-tabs ul.tabs li:hover,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-tabs .tabcordion-tab.active,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-tabs .tabcordion-tab:hover,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-contents .panel-heading .panel-title .tabcordion-collapse:not(.collapsed),
	.product-listing .all-cars-list-arch.vehicle-listing-featured .car-grid,
	.product-listing .featured-vehicles-listing-wrapper';

$cardealer_color_scheme_selectors['border-left-color']   = '.timeline > li:hover > .timeline-panel:after, .tab-vertical.tabs-left .nav-tabs > li > a:hover, .tab-vertical.tabs-left .nav-tabs > li.active > a, .post.sticky';

$cardealer_color_scheme_selectors['border-right-color']  = '.timeline > li.timeline-inverted:hover > .timeline-panel:after, .timeline > li.timeline-item:hover > .timeline-panel:after';

$cardealer_color_scheme_selectors['fill']  = '
	.feature-box .icon svg,
	ul.list li > svg,
	.car-details .nav-tabs li.active svg,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-tabs .tabcordion-tab.active svg,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-tabs .tabcordion-tab:hover svg';

/*********************************
	Secondary
/******************************** */
$cardealer_color_scheme_selectors_secondary['color'] = 'h1, h2, h3, h4, h5, h6, .blog-1 .blog-content a.link, .counter b, .car-item .price span.new-price, .car-item .price bdi.new-price, .button.border, .q-link i, .blog-2 .blog-description a, .content-box-5 a, .text-black, .tab-vertical.tabs-left .nav-tabs > li > a, .timeline > li > .timeline-badge h4, .opening-hours strong, #tabs .tabs li, .accordion .accordion-title a, .accordion .accordion-title a:after, .sorting-options-main .price-slide .price label, .sorting-options-main .price-search span, .product-listing .car-grid .car-title a, .car-details-sidebar .details-block ul li strong, .car-details .slider-for .slick-next:before, .entry-title a, .post-password-form input[type="password"], .product .price span, .woocommerce-cart table.shop_table.cart td.product-subtotal .amount, .woocommerce-cart table.shop_table.cart td.product-price .amount, .woocommerce-cart table.shop_table.cart td.product-quantity .qty, .woocommerce .woocommerce-checkout .form-row input.input-text, .woocommerce-checkout .woocommerce form.login .input-text, .woocommerce-checkout .woocommerce form.checkout_coupon .input-text, .woocommerce .woocommerce-checkout-review-order table tfoot .cart-subtotal th, .woocommerce .woocommerce-checkout-review-order table tfoot .order-total th, .woocommerce .woocommerce-checkout-review-order table tfoot .cart-subtotal .amount, .woocommerce-MyAccount-navigation ul li a, .woocommerce-account .woocommerce form .input-text, .mega-menu .widget_shopping_cart_content ul.product_list_widget li.empty, a.bbp-forum-title, li.bbp-forum-freshness a, li.bbp-reply-topic-title a, a.bbp-topic-permalink, li.bbp-topic-freshness a, a.favorite-toggle, a.subscription-toggle, a.bbp-author-name, .bbp-logged-in h4 a, #bbp-user-navigation ul li a, .car-detail-post-option > ul li a, .widget.widget_rss ul li a:hover, .widget.widget_recent_comments ul li a:hover, .widget.widget_rss ul li .rss-date, .woocommerce div.product .woocommerce-tabs .wc-tab .comment-reply-title, .item-listing > .item > .portfolio-item .portfolio-caption a, .search-logo .tabs li, .cars_condition_carousel-wrapper .cardealer-tabs .tabs li, .section-title.style_2 span,  .wpb-js-composer .entry-content .vc_tta-color-white.vc_tta-style-flat .vc_tta-panel .vc_tta-panel-title > a, .wpb-js-composer .vc_tta.vc_general.vc_tta-tabs.vc_tta-style-flat li.vc_tta-tab a, .wpcf7-form .contact-form.appointment-form.appointment-form-light input[type="text"], .wpcf7-form .contact-form.appointment-form.appointment-form-light input[type="email"], .wpcf7-form .contact-form.appointment-form.appointment-form-light textarea, .wpb-js-composer .vc_tta.vc_general.vc_tta-accordion.vc_tta-style-outline .vc_tta-panel-heading a, .wpb-js-composer .entry-content .vc_tta-color-grey.vc_tta-style-flat .vc_tta-panel .vc_tta-panel-title > a, .wpb-js-composer .entry-content .vc_tta-color-grey.vc_tta-style-flat .vc_tta-panel.vc_active .vc_tta-panel-title > a, .wpb-js-composer .entry-content .vc_tta-color-white.vc_tta-style-flat .vc_tta-panel .vc_tta-panel-title > a, .wpb-js-composer .entry-content .vc_tta-color-grey.vc_tta-style-outline .vc_tta-panel.vc_active .vc_tta-panel-title > a, .wpb-js-composer .entry-content .vc_tta-color-grey.vc_tta-style-outline .vc_tta-panel .vc_tta-panel-title > a, #header .topbar .language .drop-content a, #header.default .topbar .language ul li a .lang-label, #header.transparent-fullwidth .topbar .language ul li a .lang-label, #header.boxed .topbar .language a.cardealer-current-lang:hover, #header.boxed .topbar .language.style-horizontal ul li a:hover .lang-label, .style-classic.car-item .car-content ul.car-bottom-actions.classic-grid li a, .style-classic.car-grid .car-bottom .car-bottom-actions li a, .wp-block-latest-comments footer a:hover,
	#tabs .tabs li,
	.cardealer-tabs .tabs li,
	.cd-video-button .popup-youtube,
	.cd-compare-button .pgs_compare_popup,
	.cd-wishlist-button .pgs_wishlist,
	.cd-vehicle-attributes .car-attributes li strong,
	.cd-vehicle-attributes.style-2 .car-attributes li span,
	.cd-vehicle-breadcrumb .page-breadcrumb li.current-item span,
	.cd-vehicle-breadcrumb .page-breadcrumb li.current-item:hover span,
	.cd-vehicle-buttons.cd-vehicle-buttons-style-2 .details-nav .vehicle-buttons li a,
	.cd-vehicle-buttons.cd-vehicle-buttons-style-2 .details-nav .vehicle-buttons li a:hover,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-tabs .tabcordion-tab,
	.vehicle-tabs-tabcordion .vehicle-tabs-tabcordion-contents .panel-heading .panel-title .tabcordion-collapse,
	.cardealer-dashboard-content .cdfs-edit-account-form legend,
	.cardealer-dashboard-content .cdfs-edit-account-form .cdfs-image-upload .select-file-info .select-file-label,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-item-title a,
	.cardealer-dashboard-content .cardealer-dashboard-content-grid .cardealer-list-items-bottom .car-status span,
	.cardealer-dashboard-content .cardealer-dashboard-subs-table th,
	.cardealer-dashboard-content .cardealer-dashboard-subs-table td.woocommerce-orders-table__cell-subscription-id a,
	.cardealer-userdash-content .cardealer-userdash-tabs .all-cars-list-arch .car-grid .car-title a,
	.style-classic.car-grid .car-details .vehicle-attributes-list ul strong,
	.style-classic.car-item .vehicle-attributes-list li strong,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-dealer-average-rating-numbers .cdfs-rating,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-dealer-average-rating-numbers .cdfs-outoff-rating,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-dealer-average-rating-heading .cdfs-dealer-rating-label,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-dealer-average-rating-heading span,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-dealer-recommendations,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-dealer-recommendations .cdfs-dealer-recommendations-label,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-row-right .cdfs-single-review .cdfs-dealer-average-rating-html .cdfs-ratings-average,
	.cardealer-userdash-content .cardealer-userdash-tab-content-reviews .cdfs-row-right .cdfs-single-review .cdfs-single-label,
	.public-profile-notice a,
	.cd-vehicle-seller-info .vehicle-seller-info-details .vehicle-seller-info-author a,
	.woocommerce-Reviews .comment-reply-title,
	.cdfs-dealers-wrapper .cdfs-dealers-list-wrapper .cdfs-dealers-list th,
	.cdfs-dealers-wrapper .cdfs-dealers-list-wrapper .cdfs-dealers-list td a,
	.cdfs-dealers-wrapper .cdfs-dealers-list-wrapper .cdfs-dealers-list tbody td:before,
	.cdfs-dealers-wrapper .cdfs-dealers-list-wrapper .cdfs-dealers-list .cdfs-dealers-list-column-location .search-distance span,
	.cdfs_add_car_form .form-group label,
	.cdfs-av-sections .cdfs-av-section-cars-location .cdfs-av-section-content p a';

/*********************************
	Tertiary
/******************************** */
$cardealer_color_scheme_selectors_tertiary['color'] = 'body, .section-title span, .widget_search input, .form-group label, .feature-box.round-icon i, .call-to-action a, .counter.icon i:before, select, .price-slide .price input, .car-item .car-list li, .feature-box.round-border .icon i, .isotope-filters  button, .wpcf7-form input[type="text"], .wpcf7-form input[type="email"], .wpcf7-form textarea, .widget_recent_entries .recent-post-info span, caption, .widget ul li a, .widget_recent_entries .recent-post-info i, .sorting-options-main .price-slide .price input, .pagination li a, .pagination > li > a, .pagination > li > span, .product-listing .car-grid .price span.old-price, .car-details .car-price .old-price, .details-nav ul li a, .car-details .car-price .old-price, .car-details .slider-for .slick-prev:before, .entry-meta ul li a, .entry-meta a, .tags-2 ul li a, .woocommerce nav.woocommerce-pagination ul li a, .pagination ul li a, .woocommerce nav.woocommerce-pagination ul li span, .pagination ul li span, .error-404 .error-content p, .countdown li p, #buddypress div#item-header div#item-meta, #buddypress .activity-list .activity-content .activity-header, #buddypress .activity-list .activity-content .comment-header, .cd_maintenance .mc4wp-form .form-control, .widget_recent_entries .recent-post-info a, .form-control, .section-field input, .section-field textarea, .section-title.style_2 h2, .wpb-js-composer .entry-content .vc_tta-color-grey.vc_tta-style-outline .vc_tta-panel .vc_tta-panel-title > a, .wpb-js-composer .entry-content .vc_tta-color-grey.vc_tta-style-outline .vc_tta-panel.vc_active .vc_tta-panel-title > a, .wp-block-latest-comments footer, .select2-container .select2-selection--single .select2-selection__rendered';
